version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: codevision_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codevision
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: code-vision-codevision-api
    container_name: codevision_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # Railway style DATABASE_URL
      DATABASE_URL: postgresql://postgres:postgres@db:5432/codevision
      UI_ORIGINS: http://localhost:3001,https://localhost:3001
    ports:
      - "8080:8080"

  ui:
    image: code-vision-codevision-ui
    container_name: codevision_ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ApiSettings__BaseUrl: http://api:8080
    ports:
      - "3001:8080"

volumes:
  db_data:

